// This source code file is AUTO-GENERATED by github.com/taskcluster/jsonschema2go

package model

type (
	// AMQP API
	AMQPAPI struct {

		// A schema conformant to `$ROOT_URL/references/pulse.json` describing AMQP API exposed by service.
		Reference string `json:"reference"`

		// Version of API, e.g. `v1`.
		//
		// Syntax:     ^v[0-9][0-9\.\-]*$
		Version string `json:"version"`
	}

	// HTTP API
	HTTPAPI struct {

		// A schema conformant to `$ROOT_URL/references/http.json` describing HTTP API exposed by service.
		Reference string `json:"reference"`

		// Version of API, e.g. `v1`.
		//
		// Syntax:     ^v[0-9][0-9\.\-]*$
		Version string `json:"version"`
	}

	// A taskcluster service that exposes an HTTP/AMQP API.
	Service struct {

		// HTTP API exposed by this service.
		//
		// Default:    []
		Apis []HTTPAPI `json:"apis,omitempty"`

		// AMQP 0.9 API exposed by this service.
		//
		// Default:    []
		Pulse []AMQPAPI `json:"pulse,omitempty"`

		// A short name for the service, such as `queue` / `purge-cache` / `ec2-manager`.
		//
		// Syntax:     ^[a-z][a-z0-9\-]*$
		ServiceName string `json:"serviceName"`
	}

	// Manifest of taskcluster service definitions available in a taskcluster service deployment.
	// These manifests are served from `$ROOT_URL/references/manifest.json`.
	//
	// See https://github.com/taskcluster/taskcluster-references for further information.
	TaskclusterServiceManifest struct {

		// List of services that comprise a taskcluster build.
		//
		// Default:    []
		Services []Service `json:"services"`
	}
)
